# Generated by Django 3.0.3 on 2020-11-20 00:04

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('message', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('inquiry', models.CharField(max_length=400)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Not Required', max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('operations', models.CharField(max_length=1000)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('email', models.CharField(max_length=100)),
                ('num_employee', models.IntegerField()),
                ('payroll', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pets',
        ),
    ]
